const app = document.querySelector('#app-main');
const menu = document.querySelector('.nav-menu');
const toggle = document.querySelector('.menu-toggle');
document.querySelector('#year').textContent = new Date().getFullYear();

const demoArticles = [
  {type:'Berita', title:'Pelantikan DPM FIPP UNIMA Periode 2026–2027', text:'Pengurus DPM FIPP UNIMA resmi memulai periode pengabdian.', image:'png/berita1.png'},
  {type:'Kajian', title:'Membaca Kebutuhan Ruang Belajar Mahasiswa', text:'Kajian awal untuk mendorong fasilitas belajar yang inklusif.', image:'png/berita2.png'},
  {type:'Pengumuman', title:'Aspirasi Mahasiswa Kini Lebih Terarah', text:'Gunakan D-DAS untuk mengirim isu dan melacak penanganannya.', image:'png/hero-bgk.png'}
];
const demoOrmawa = ['BEM FIPP UNIMA','KPRM FIPP UNIMA','HIMAPSI JPPB','HIMAPRO PGSD','HIMAPRO BK','HIMAPRO PKH','HIMAPRO PG-PAUD','UPK-MK FIPP','BTM FIPP','KMK FIPP','MHDI FIPP','MAPALA PAEDAGOGIC'];
let articles = [...demoArticles];
let ormawa = [...demoOrmawa];
let isLiveData = false;
const esc = value => String(value || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const pageHead = (eyebrow,title,text) => `<header class="page-head"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${text}</p></header>`;
const articleCards = (items=articles) => `<div class="article-grid">${items.map(a=>`<article class="article-card"><img src="${esc(a.image)}" alt=""/><div><span class="badge">${esc(a.type)}</span><h3>${esc(a.title)}</h3><p>${esc(a.text)}</p></div></article>`).join('')}</div>`;

function home(){return `<section class="page"><section class="hero"><div class="hero-inner"><p class="eyebrow">Portal Digital Kelembagaan</p><h1>Suara mahasiswa, kerja yang terbuka.</h1><p>DPM FIPP UNIMA hadir untuk menerima aspirasi, mengawal kebijakan, dan membagikan informasi kelembagaan secara transparan.</p><div class="button-row"><a class="btn btn-primary" href="#/d-das">Sampaikan Aspirasi →</a><a class="btn btn-outline" href="#/monitoring">Lihat Transparansi</a></div></div></section><section class="section split"><div><p class="eyebrow">DPM FIPP UNIMA</p><h2>Parlemen mahasiswa yang mudah dijangkau.</h2><p>Portal ini menyatukan informasi organisasi, kajian, legislasi, program kerja, dan arsip digital dalam satu ruang yang dapat diakses mahasiswa.</p></div><aside class="feature-panel"><p class="eyebrow">Akses cepat</p><h2>D-DAS</h2><p>Sampaikan aspirasi dengan aman. Saat database terhubung, Anda dapat menerima nomor tiket dan memantau penanganannya.</p><a class="btn btn-primary" href="#/d-das">Mulai aspirasi</a></aside></section><section class="section"><div class="section-title"><div><p class="eyebrow">Layanan digital</p><h2>Satu sistem, fungsi kelembagaan terhubung.</h2></div></div><div class="card-grid"><article class="card"><div class="icon">A</div><h3>D-DAS</h3><p>Kanal aspirasi dan pengawalan isu mahasiswa.</p><a class="text-link" href="#/d-das">Kirim aspirasi →</a></article><article class="card"><div class="icon">S</div><h3>D-SIGHT</h3><p>Kajian, opini, dan produk pemikiran DPM.</p><a class="text-link" href="#/kajian">Baca kajian →</a></article><article class="card"><div class="icon">T</div><h3>D-TRACE</h3><p>Monitoring progres, laporan, dan akuntabilitas.</p><a class="text-link" href="#/monitoring">Lihat monitoring →</a></article></div></section><section class="section"><div class="section-title"><div><p class="eyebrow">Transparansi</p><h2>Ringkasan kerja periode aktif</h2></div><p>Angka berikut adalah tampilan contoh hingga data kelembagaan tersambung.</p></div><div class="stat-grid"><div class="stat"><strong>24</strong><span>Aspirasi ditangani</span></div><div class="stat"><strong>8</strong><span>Program kerja aktif</span></div><div class="stat"><strong>12</strong><span>ORMAWA terhubung</span></div><div class="stat"><strong>6</strong><span>Publikasi periode ini</span></div></div></section><section class="section"><div class="section-title"><div><p class="eyebrow">Publikasi terbaru</p><h2>Informasi dari DPM</h2></div><a class="text-link" href="#/berita">Semua publikasi →</a></div>${articleCards()}</section></section>`}
function about(){return `<section class="page">${pageHead('Tentang DPM','Bekerja untuk representasi mahasiswa.','DPM FIPP UNIMA menjalankan fungsi legislasi, pengawasan, penyerapan aspirasi, dan pengkajian untuk lingkungan FIPP yang lebih baik.')}<section class="section split"><div><p class="eyebrow">Visi</p><h2>Aspiratif, transparan, kritis, dan berdampak.</h2><p>Mendorong DPM FIPP UNIMA sebagai rumah representasi mahasiswa yang responsif dan bertanggung jawab.</p></div><div><p class="eyebrow">Misi</p><div class="card"><p>01 — Mengawal aspirasi mahasiswa secara terbuka.</p><p>02 — Menguatkan fungsi legislasi dan pengkajian.</p><p>03 — Mendorong transparansi kinerja ORMAWA.</p><p>04 — Menyediakan arsip digital yang mudah diakses.</p></div></div></section><section class="section"><p class="eyebrow">Struktur periode aktif</p><h2>Komisi dan pengurus</h2><div class="directory">${['Ketua DPM','Wakil Ketua DPM','Sekretaris','Komisi 1 — Legislasi & Kajian','Komisi 2 — Aspirasi & Pengawasan','Bendahara'].map((item,i)=>`<article><small>Posisi ${String(i+1).padStart(2,'0')}</small><h3>${item}</h3><p>Data pengurus akan dikelola melalui Admin Panel berdasarkan periode aktif.</p></article>`).join('')}</div></section></section>`}
function ddas(){return `<section class="page">${pageHead('D-DAS','Sampaikan aspirasi dengan aman.','Digital Aspiration System adalah ruang resmi untuk menyampaikan isu, masukan, atau laporan kepada DPM FIPP UNIMA.')}<section class="section split"><div><p class="eyebrow">Formulir aspirasi</p><h2>Ceritakan isu Anda secara jelas.</h2><p class="notice">Mode demonstrasi: formulir ini belum mengirim atau menyimpan data pribadi. Saat layanan database aktif, verifikasi dan nomor tiket akan diproses dengan aman.</p><form class="form-shell" id="aspiration-form"><div class="field-grid"><label class="field"><span>Kategori</span><select required><option value="">Pilih kategori</option><option>Akademik</option><option>Fasilitas</option><option>ORMAWA</option><option>Etika & keamanan</option></select></label><label class="field"><span>Tujuan aspirasi</span><select required><option value="">Pilih tujuan</option><option>DPM FIPP UNIMA</option><option>ORMAWA terkait</option><option>Fakultas</option></select></label><label class="field full"><span>Judul singkat</span><input required maxlength="120" placeholder="Contoh: Perbaikan fasilitas ruang belajar" /></label><label class="field full"><span>Uraian aspirasi</span><textarea required maxlength="3000" placeholder="Jelaskan masalah, lokasi/waktu, dan usulan tindak lanjut."></textarea></label></div><label class="checkbox"><input type="checkbox" required /><span>Saya memahami bahwa informasi sensitif akan diverifikasi sebelum dikirim dan saya setuju dengan ketentuan layanan.</span></label><button class="btn btn-primary" type="submit">Lanjut ke verifikasi</button><p class="form-status" aria-live="polite"></p></form></div><aside class="feature-panel"><p class="eyebrow">Alur penanganan</p><h2>Dikirim → Ditinjau → Ditindaklanjuti</h2><p>Aspirasi yang telah diverifikasi akan menerima tiket. Komisi yang berwenang meninjau, meneruskan jika diperlukan, serta memperbarui status tindak lanjut.</p><p><strong>Catatan:</strong> Laporan sensitif membutuhkan bukti dan perlindungan khusus.</p></aside></section></section>`}
function listing(kind,title,desc){const filtered=kind==='Publikasi'?articles:articles.filter(a=>a.type.toLowerCase()===kind.toLowerCase());const sourceNote=isLiveData?'Data publik dibaca langsung dari Supabase dan hanya menampilkan konten berstatus published.':'Konten di atas merupakan data contoh. Kelak daftar, filter, dan detail akan dibaca dari CMS yang telah disetujui.';return `<section class="page">${pageHead(kind,title,desc)}<section class="section"><div class="filters"><button class="active">Semua</button><button>Kajian</button><button>Berita</button><button>Pengumuman</button></div>${articleCards(filtered.length?filtered:articles)}<div class="empty" style="margin-top:1rem">${sourceNote}</div></section></section>`}
function monitoring(){return `<section class="page">${pageHead('D-TRACE','Pantau pekerjaan yang dapat dipertanggungjawabkan.','Digital Transparency & Accountability Center menyajikan perkembangan kegiatan dan laporan yang telah disetujui untuk dipublikasikan.')}<section class="section"><div class="card"><p class="eyebrow">Contoh monitoring</p>${[['Tindak lanjut ruang belajar',75],['Evaluasi program kerja ORMAWA',50],['Publikasi hasil sidang',100],['Kajian layanan akademik',25]].map(x=>`<div class="progress-row"><strong>${x[0]}</strong><div class="progress" aria-label="${x[1]}% selesai"><i style="width:${x[1]}%"></i></div><b>${x[1]}%</b></div>`).join('')}</div></section></section>`}
function archive(){return `<section class="page">${pageHead('D-DAR','Arsip digital yang terkelola.','Digital Archive & Document Repository akan menyimpan dokumen kelembagaan berdasarkan periode, kategori, dan tingkat akses.')}<section class="section"><div class="filters"><button class="active">Semua dokumen</button><button>Sidang</button><button>Kajian</button><button>Legislasi</button><button>LPJ</button></div><div class="directory">${['Arsip Sidang Mahasiswa','Naskah Kajian','Dokumen Legislasi','Laporan Pertanggungjawaban','Surat Kelembagaan','Dokumen ORMAWA'].map((x,i)=>`<article><small>${i%3===0?'Publik':'Terbatas'}</small><h3>${x}</h3><p>Filter berdasarkan periode, kategori, dan status arsip akan tersedia saat repository terhubung.</p></article>`).join('')}</div></section></section>`}
function ormawaPage(){return `<section class="page">${pageHead('ORMAWA FIPP','Organisasi mahasiswa dalam satu ekosistem.','Profil dan publikasi ORMAWA akan diperbarui langsung melalui panel administrasi pada setiap periode.')}<section class="section"><div class="directory">${ormawa.map((x,i)=>`<article><small>ORMAWA ${String(i+1).padStart(2,'0')}</small><h3>${esc(x)}</h3><p>Profil, struktur, kontak yang dipublikasikan, dan dokumentasi program.</p></article>`).join('')}</div></section></section>`}
function admin(){const route=location.hash.split('/').slice(2).join('/')||'dashboard';const title={dashboard:'Dashboard',aspirasi:'D-DAS — Aspirasi',kajian:'D-SIGHT — Kajian',legislasi:'Legislasi',monitoring:'D-TRACE — Monitoring',laporan:'Laporan',berita:'Publikasi',survei:'Survei',approval:'Approval',requests:'Request Access',media:'Media',organization:'Organisasi & Periode',users:'Pengguna',audit:'Audit Log'}[route]||'Admin Panel';const links=[['dashboard','Dashboard'],['aspirasi','D-DAS'],['kajian','D-SIGHT'],['legislasi','Legislasi'],['monitoring','D-TRACE'],['laporan','Laporan'],['berita','Publikasi'],['survei','Survei'],['approval','Workflow Approval'],['requests','Request Access'],['media','Media'],['organization','Organisasi & Periode'],['users','Pengguna'],['audit','Audit Log']];return `<section class="admin"><aside class="admin-sidebar"><div class="admin-brand">DPM FIPP · ADMIN</div><label class="sr-only" for="demo-role">Role tampilan</label><select id="demo-role" class="role-select"><option>Super Admin (demo)</option><option>Sekretaris (demo)</option><option>Komisi 1 (demo)</option><option>Komisi 2 (demo)</option><option>Viewer (demo)</option></select><nav class="admin-nav">${links.map(x=>`<a class="${route===x[0]?'active':''}" href="#/admin/${x[0]}">${x[1]}</a>`).join('')}</nav></aside><div class="admin-content"><div class="admin-top"><div><p class="eyebrow">Mode prototipe</p><h1>${title}</h1><p>Struktur antarmuka untuk pengelolaan sistem DPM FIPP UNIMA.</p></div><a class="btn btn-primary" href="#/admin/berita">+ Buat konten</a></div><div class="admin-alert">Akses dan tombol pada prototipe ini belum terhubung ke autentikasi atau database. Role sebenarnya akan dicek di server dan RLS, bukan hanya dari tampilan.</div><div class="admin-cards"><div class="admin-kpi"><span>Menunggu approval</span><strong>7</strong></div><div class="admin-kpi"><span>Aspirasi aktif</span><strong>12</strong></div><div class="admin-kpi"><span>Request akses</span><strong>3</strong></div><div class="admin-kpi"><span>Publikasi bulan ini</span><strong>6</strong></div></div><section class="admin-panel"><h2>${route==='approval'?'Antrian persetujuan':'Aktivitas terbaru'}</h2><table class="table"><thead><tr><th>Item</th><th>Modul</th><th>Status</th><th>Aksi</th></tr></thead><tbody><tr><td>Kajian layanan akademik</td><td>D-SIGHT</td><td><span class="status waiting">PENDING SECRETARY</span></td><td><button class="admin-action">Tinjau</button></td></tr><tr><td>Dokumen hasil sidang</td><td>D-DAR</td><td><span class="status private">DRAFT</span></td><td><button class="admin-action">Buka</button></td></tr><tr><td>Aspirasi fasilitas kelas</td><td>D-DAS</td><td><span class="status">IN REVIEW</span></td><td><button class="admin-action">Kelola</button></td></tr></tbody></table></section></div></section>`}
function notFound(){return `<section class="section page"><div class="empty"><h1>Halaman tidak ditemukan</h1><p>Silakan kembali ke beranda.</p><a class="btn btn-primary" href="#/">Beranda</a></div></section>`}
function render(){const path=location.hash.replace(/^#\/?/,'')||'/';const routes={'/':home,'tentang':about,'d-das':ddas,'kajian':()=>listing('Kajian','Kajian dan produk pemikiran','D-SIGHT adalah pusat kajian, opini, kebijakan, dan produk pemikiran DPM.'),'berita':()=>listing('Berita','Publikasi DPM','Berita, pengumuman, artikel, dan informasi lain yang telah dipublikasikan.'),'monitoring':monitoring,'arsip':archive,'ormawa':ormawaPage};app.innerHTML=path.startsWith('admin')?admin():(routes[path]?routes[path]():notFound());document.querySelectorAll('.nav-menu a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#/${path}`));menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'instant'});bind()}
function bind(){document.querySelector('#aspiration-form')?.addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('.form-status').textContent='Formulir siap. Integrasi OTP, CAPTCHA, private storage, dan nomor tiket akan diaktifkan bersama database.'});document.querySelectorAll('.filters button').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}))}
async function getPublicRows(config, table, query) {
  const response = await fetch(`${config.url}/rest/v1/${table}?${query}`, {
    headers: {
      apikey: config.publishableKey,
      Authorization: `Bearer ${config.publishableKey}`,
    },
  });
  if (!response.ok) throw new Error(`Supabase tidak dapat memuat ${table}.`);
  return response.json();
}

function publicImage(config, path, fallback) {
  if (!path) return fallback;
  if (/^https?:\/\//i.test(path)) return path;
  const cleanPath = String(path).replace(/^\/+/, '').replace(/^dpm-public\//, '');
  return `${config.url}/storage/v1/object/public/dpm-public/${encodeURIComponent(cleanPath).replace(/%2F/g, '/')}`;
}

async function loadPublicData() {
  try {
    const configResponse = await fetch('/api/public-config');
    if (!configResponse.ok) return;
    const config = await configResponse.json();
    const [contentsResult, organizationsResult] = await Promise.allSettled([
      getPublicRows(config, 'contents', 'select=id,title,slug,type,excerpt,featured_image_path,published_at&status=eq.published&deleted_at=is.null&order=published_at.desc&limit=12'),
      getPublicRows(config, 'organizations', 'select=*&status=eq.active&deleted_at=is.null&limit=100'),
    ]);
    if (contentsResult.status === 'fulfilled' && contentsResult.value.length) {
      articles = contentsResult.value.map(item => ({
        type: String(item.type || 'Publikasi').replace(/_/g, ' '),
        title: item.title,
        text: item.excerpt || 'Baca informasi selengkapnya dari DPM FIPP UNIMA.',
        image: publicImage(config, item.featured_image_path, 'png/hero-bgk.png'),
      }));
      isLiveData = true;
    }
    if (organizationsResult.status === 'fulfilled' && organizationsResult.value.length) {
      const names = organizationsResult.value.map(item => item.name || item.organization_name || item.title).filter(Boolean);
      if (names.length) ormawa = names;
    }
    render();
  } catch (_error) {
    // The public portal remains usable with safe static placeholders while offline.
  }
}

toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});window.addEventListener('hashchange',render);render();loadPublicData();
